title: Mediclassics Articles
description: "Articles for Traditional Medicine of East Asian"
author:
  name: "Junho Oh"
  email: "pinedance@gmail.com"
  url: "https://pinedance.github.io"

google_analytics: UA-72863252-4
baseurl: /mediclassics

source: .
# destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page/:num/


# Build settings
host: localhost
port: 8384

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

markdown: kramdown
future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Junho"
year : "2019"

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", ".gitignore", "ref_data" ]
